### ISSUE TITLE
Implement Data Processing

### ISSUE THREAD

**Issue by mhueppe** [mhueppe/machineLearningProject_jaNoMi#8]
Implement data cleaning: 
- Replace all years in the abstract by "years"
- Replace all authors in the abstract by "author"
- Replace all conference/journal mentions by "publication"

This should help the model to learn that the above three information is not important for the title

**Comment by nllink** [comment]
The normal spacy model for English NER (named entity recognition) seems to perform pretty bad on our domain specific dataset. We need to find a better one (possibly scispacy https://allenai.github.io/scispacy/)
